
-include ../.config

subdir-y += fonts
subdir-y += configs
subdir-y += lib
subdir-$(CONFIG_WIDGET_LIBRARY)   += widget
subdir-$(CONFIG_DEMO_APPLICATIONS) += ../demo
subdir-$(CONFIG_THEME_PLUGIN) += themes
subdir-y += server

include ../Makefile.lib
