
INCDIR := $(INCDIR)
LIBDIR := $(LIBDIR)

CFLAGS   := $(addprefix -I,$(INCDIR)) $(CFLAGS)
CXXFLAGS := $(CFLAGS) $(CXXFLAGS)
CPPFLAGS := $(CFLAGS) $(CXXFLAGS)
ASFLAGS  := $(CFLAGS) $(ASFLAGS)
LDFLAGS  := $(addprefix -L,$(LIBDIR)) $(LDFLAGS)
DEPEND   := Makefile.depend

all: $(EXTRA_TARGETS) $(TARGET) $(TARGET_A) $(TARGET_SO)

ifdef TARGET
$(TARGET): $(OBJS) $(EXTRA_OBJS)
	rm -rf $@
	$(CC) $^ $(LDFLAGS) -o $@
endif

ifdef TARGET_A
$(TARGET_A): $(OBJS)
	rm -rf $@
	$(AR) $@ $^
	$(RANLIB) $@
endif

ifdef TARGET_SO
$(TARGET_SO): $(OBJS)
	rm -rf $@
	$(CC) -g -shared -o $@ $^ $(LDFLAGS)
endif

.c.o:
	$(CC) $(CFLAGS) -c -o $@ $<

.cpp.o:
	$(CXX) $(CXXFLAGS) -c -o $@ $<

$(DEPEND): $(EXTRA_DEPEND_FILES) $(OBJS:.o=.c)
	@>$(DEPEND)
	@$(foreach F, $(OBJS:.o=.c), $(CC) $(CFLAGS) -MT $(F:.c=.o) -MM $(F) >> $(DEPEND);)
-include $(DEPEND)

clean:
	rm -f $(TARGET) $(TARGET_A) $(TARGET_SO) $(EXTRA_CLEAN) $(OBJS) $(EXTRA_TARGETS) $(DEPEND)
