
-include ../.config

subdir-$(CONFIG_DEMO_CHILD)    = child
subdir-$(CONFIG_DEMO_DESKTOP) += desktop
subdir-$(CONFIG_DEMO_HIDE)    += hide
subdir-$(CONFIG_DEMO_LOAD)    += load
subdir-$(CONFIG_DEMO_SIMPLE)  += simple
subdir-$(CONFIG_DEMO_OBJECT)  += object
subdir-$(CONFIG_DEMO_TEMP)    += temp
subdir-$(CONFIG_DEMO_TERM)    += term
subdir-$(CONFIG_DEMO_TIMER)   += timer
subdir-$(CONFIG_DEMO_LOGOUT)  += xynthlogout
subdir-$(CONFIG_DEMO_IMAGE)   += img
subdir-$(CONFIG_DEMO_ONSCREENKEYBOARD) += onscreenkeyboard
subdir-$(CONFIG_DEMO_WIDGETX) += widgetx
subdir-$(CONFIG_DEMO_XDIALOG) += xdialog

include ../Makefile.lib
