
-include ../../../.config

target_o-y = libpng.o

libpng.o_includes-y = ./ \
                      ../libz
libpng.o_files-y = png.c \
                   pngerror.c \
                   pngget.c \
                   pngmem.c \
                   pngpread.c \
                   pngread.c \
                   pngrio.c \
                   pngrtran.c \
                   pngrutil.c \
                   pngset.c \
                   pngtrans.c \
                   pngwio.c \
                   pngwrite.c \
                   pngwtran.c \
                   pngwutil.c

include ../../../Makefile.lib
