
include ../../../Makefile.cfg
include ../../../Makefile.parse

DIR = src/lib/libpng/

INCDIR = ./ ../libz
OBJS += png.o pngerror.o pngget.o pngmem.o \
        pngpread.o pngread.o pngrio.o pngrtran.o \
        pngrutil.o pngset.o pngtrans.o pngwio.o \
        pngwrite.o pngwtran.o pngwutil.o

TARGET_O = libpng.o

include ../../../Makefile.rules
