
-include ../../../.config

target_o-y = libpixman.o

libpixman.o_includes-y = ./
libpixman.o_cflags-y = -DHAVE_CONFIG_H
libpixman.o_files-y = fbcompose.c \
                      fbedge.c \
                      fbpict.c \
                      fbtrap.c \
                      icblt.c \
                      icbltone.c \
                      iccolor.c \
                      icformat.c \
                      icimage.c \
                      icpixels.c \
                      icrect.c \
                      icstipple.c \
                      ictransform.c \
                      ictrap.c \
                      ictri.c \
                      icutil.c \
                      pixregion.c \
                      renderedge.c

include ../../../Makefile.lib
