
include ../../../Makefile.cfg
include ../../../Makefile.parse

DIR = src/lib/expat/

INCDIR = ./
CFLAGS += -DHAVE_EXPAT_CONFIG_H
OBJS += xmlparse.o xmltok.o xmlrole.o

TARGET_O = libexpat.o

include ../../../Makefile.rules
