
target_o-y = libexpat.o

libexpat.o_files-y = xmlparse.c \
                     xmltok.c \
                     xmlrole.c
libexpat.o_includes-y = ./
libexpat.o_cflags-y = -DHAVE_EXPAT_CONFIG_H

include ../../../Makefile.lib
