
include ../../Makefile.cfg
include ../../Makefile.parse

INCDIR  = ../../src/lib ../../src/server
LIBDIR  = ../../src/lib
LDFLAGS = $(LIBDIR)/libxynth.a -lpthread -lm

OBJS = theme.o

TARGET_HOST = theme

include ../../Makefile.rules
