
target.host-y = theme

theme_includes-y  = ../../src/lib ../../src/server
theme_libraries-y = ../../src/lib
theme_ldflags-y   = -lxynth -lpthread -lm -static
theme_files-y     = theme.c

include ../../Makefile.lib
