
target_o-y = libz.o

libz.o_includes-y = ./

libz.o_files-y = adler32.c \
                 compress.c \
                 crc32.c \
                 gzio.c \
                 uncompr.c \
                 deflate.c \
                 trees.c \
                 zutil.c \
                 inflate.c \
                 infback.c \
                 inftrees.c \
                 inffast.c

include ../../../Makefile.lib
