
include ../../Makefile.cfg
include ../../Makefile.parse

INCDIR  = ../../src/lib ../../include
LIBDIR  = ../../src/lib
LDFLAGS = $(LIBDIR)/libxynth.a -lpthread -lm

OBJS = theme.o

TARGET = theme

include ../../Makefile.rules
