
target_o-y = lxdialog.o

lxdialog.o_files-y = checklist.c \
                     menubox.c \
                     textbox.c \
                     yesno.c \
                     inputbox.c \
                     util.c \
                     msgbox.c

include ../../../Makefile.lib
